### ISSUE TITLE
用到了哪些capabilities？我想build一个在未root的Android上用

### ISSUE THREAD

**Issue by livilivi** [cnbatch/udphop#11]
请问用到了那些网络相关的capabilities呢？
我不太确定我build一个arm64的Linux二进制能否在termux的proot环境下跑起来。

**Comment by cnbatch** [comment]
都是很寻常的TCP以及UDP
在普通的系统状况下，非root用户也能跑起来，我做测试和debug时就是用非root用户的
Android环境不清楚，理论上来说应该是能用的

**Comment by livilivi** [comment]
好的，感谢回复，我试试，如果可以会在这里反馈。

**Comment by livilivi** [comment]
Android13正常使用，要单独编译一下botan3，asio。静态链接, termux没有相关的包。
