### ISSUE TITLE
客户端之间能直连吗?

### ISSUE THREAD

**Issue by jsyzjhj** [cnbatch/udphop#4]
客户端之间能直连吗?

**Comment by cnbatch** [comment]
这种“客户端”的本质其实就是“客户端+服务端”集合体，看起来客户端可以直连，实际上是因为客户端本身也在做服务端的任务，或者说服务端同时也在做客户端的任务。例如BT软件就是这样。

udphop的本质其实就仅仅是个数据转发器。<br>
客户端：侦听指定端口，将这个端口收到的数据转发至另一个位置；另一个位置返回的数据从侦听的指定端口发回给实际需要数据的程序。<br>
服务端：侦听指定端口或端口范围，将接收到的数据同样转发至另一个指定位置；从另一个位置返回的数据再通过侦听的端口发回给客户端。

因此，如果需要两端任意方向传数据，那就需要两边同时建立服务端和客户端。<br>
就像这样：`udphop server.conf client.conf` <br>
udphop本身可以同时接受多个配置文件，只要它们之间的监听端口并未互相冲突就行。

不知道这种需要两边直连双向互通的场景是什么，如果是BT软件，那么意义不大，不可能要求每个人都装上udphop，何况BT协议还能用TCP。<br>
如果是syncthing这样的BT协议同步软件，要是真的遇到了UDP限速，倒不如配置成固定使用TCP。<br>
如果是frp的话，我没用过，不清楚它怎么做的。内网组网我是用wireguard和openvpn，这也是我制作udphop的原因之一。
