### ISSUE TITLE
运行几天后出现端口封锁的情况

### ISSUE THREAD

**Issue by bhzhu203** [cnbatch/udphop#5]
运行几天后出现端口封锁的情况，服务端只能换另外一个端口解决，原端口无法使用，是要降低dport_refresh的值才能避免吗

```
mode=server
listen_port=4012
destination_port=4000
destination_address=::1
encryption_password=xxxxxx
encryption_algorithm=chacha20
log_path=/tmp
```

```
mode=client
listen_port=4444
destination_port=4012
destination_address=41.111.111.11
dport_refresh=3600
encryption_password=xxxxxx
encryption_algorithm=chacha20

```

**Comment by bhzhu203** [comment]
服务端的4012的端口被封锁

**Comment by cnbatch** [comment]
是的，dport_refresh的数值较低才更好。
不填数值的话，默认60秒，如果直接就在公网上使用，完全可以设置到最低极限（现时的版本为20秒），毕竟无须考虑NAT性能消耗。

一般来说，1~2分钟应该足够使用，部分“宽松”点的区域运营商可以设定到5~10分钟。当然了，最终还得视乎各地运营商的实际情况来调整。

**Comment by cnbatch** [comment]
Server端有公网IP的话，同样应该尽可能使用多端口模式，端口范围也是越宽越好。

stun_server是给没有公网IP但又需要用Server模式的用户拿来做NAT打洞的，这项功能来自于我制作的另一个工具：https://github.com/cnbatch/PunchNAT

由于NAT打洞后获得的端口往往并不固定，如果多端口模式也用NAT打洞，就会导致原本想侦听的一段连续端口范围变成了一堆“杂乱无章”的端口列表，万一NAT过期（如果运营商NAT过期间隔太短的话）、PPPoE强制断线重连导致IP发生变化，那么这串端口列表也会随之发生变化，不但用起来十分麻烦，同时也有可能会增加stun服务器的负担。

因此在开启了NAT打洞的情况下只允许服务端使用单端口。为了让这种情况下也能让“动态端口”功能尽可能生效，client会无条件更换自己的端口，无论server模式的端口是否单一固定。

**Comment by bhzhu203** [comment]
服务端配置了范围端口，客户端也配置了范围端口（客户端配置了dport_refresh=120）

但是一天过去了，用tcpdump观察发现服务端端口一直没有变化，反而客户端端口一直在变。结果是服务端一直没有变化的那个端口被封了

服务端也有dport_refresh的参数吗

**Comment by cnbatch** [comment]
查了半天才发现原来是我搞错了版本，在Github建立仓库的时候把我的自家git仓库的旧版本复制了出来，然而真正做好的版本仍然在另一台电脑上却忘了合并上传🫠

结果Github仓库后面这些fix bug全是基于旧代码的，重新合并花费了我一整天的时间😑
同时还浪费了大家的时间，真是抱歉啊

合并后的新版本：
https://github.com/cnbatch/udphop/releases/tag/v0.4

**Comment by bhzhu203** [comment]
目前观察到最新版本服务端的端口已随机分配 :+1:
