### ISSUE TITLE
v2ex上过来的，提个请求，让 客户端<—>服务端 支持双向互传

### ISSUE THREAD

**Issue by aa51513** [cnbatch/udphop#6]
家宽互联，其中老家的移动宽带没有公网IP，但测过了NAT，是锥型

现住处是电信宽带，有公网IP，并且挂上了DDNS，可以当作伪固定IP

想让两边建立UDP通道，能够互相发起传输数据

有办法可以实现吗

如果不行，能够从电信访问移动（类似于实现隧道），也是很好的

**Comment by cnbatch** [comment]
如果有OpenVPN或者WireGuard，那么就容易多了：
OpenVPN监听端口 ↔ udphop（服务端模式） ↔ 电信网络 ↔ 移动网络 ↔ udphop（客户端模式，连接电信IP地址） ↔ OpenVPN连接本机udphop端口

反过来做也可以：
OpenVPN监听端口↔ udphop（服务端模式 + STUN参数用于打洞） ↔ 移动网络 ↔ 电信网络 ↔udphop（客户端模式，连接移动网络打洞后的 IP地址:端口） ↔ OpenVPN连接本机udphop端口

只要这个VPN隧道一直有流量，那么其中一侧的IP地址自动更换之后，udphop也能继续保持连接状态。
流量不用很大，即使只有十几KB/s都可以。
流量不间断对于“移动网络自己打洞做服务端”这种情况尤为重要，这样流量不中断可以使其中一侧udphop自动更新对端IP地址和端口的缓存。一旦中断那就麻烦了（例如长达几分钟没数据，两侧IP地址都发生了变化），因为不可能事先知道重新打洞后分配到的端口号是多少，只能修改配置文件重新连接了。

以udphop目前的设计来说，即使是移动网络重新分配了新的“洞”，只要电信那一侧的IP地址没变化，并且VPN没断开，那么VPN服务器（移动）往客户端（电信）发送数据时，电信侧的udphop会自动刷新 IP:port 的缓存，连接不会中断。

总结下来就是，如果能够保证两侧的IP地址不会同时更换，那么流量是否间断并不重要；要不然就让流量不间断。
OpenVPN和WireGuard都有心跳包选项（OpenVPN配置keepalive，WireGuard配置PersistentKeepalive），应该够用。

**Comment by aa51513** [comment]
> 如果有OpenVPN或者WireGuard，那么就容易多了： OpenVPN监听端口 ↔ udphop（服务端模式） ↔ 电信网络 ↔ 移动网络 ↔ udphop（客户端模式，连接电信IP地址） ↔ OpenVPN连接本机udphop端口
> 
> 反过来做也可以： OpenVPN监听端口↔ udphop（服务端模式 + STUN参数用于打洞） ↔ 移动网络 ↔ 电信网络 ↔udphop（客户端模式，连接移动网络打洞后的 IP地址:端口） ↔ OpenVPN连接本机udphop端口
> 
> 只要这个VPN隧道一直有流量，那么其中一侧的IP地址自动更换之后，udphop也能继续保持连接状态。 流量不用很大，即使只有十几KB/s都可以。 流量不间断对于“移动网络自己打洞做服务端”这种情况尤为重要，这样流量不中断可以使其中一侧udphop自动更新对端IP地址和端口的缓存。一旦中断那就麻烦了（例如长达几分钟没数据，两侧IP地址都发生了变化），因为不可能事先知道重新打洞后分配到的端口号是多少，只能修改配置文件重新连接了。
> 
> 以udphop目前的设计来说，即使是移动网络重新分配了新的“洞”，只要电信那一侧的IP地址没变化，并且VPN没断开，那么VPN服务器（移动）往客户端（电信）发送数据时，电信侧的udphop会自动刷新 IP:port 的缓存，连接不会中断。
> 
> 总结下来就是，如果能够保证两侧的IP地址不会同时更换，那么流量是否间断并不重要；要不然就让流量不间断。 OpenVPN和WireGuard都有心跳包选项（OpenVPN配置keepalive，WireGuard配置PersistentKeepalive），应该够用。

感谢解惑，我明白了，我按照您的思路去试试
